package net.lightskin.farworld.world;

import org.apache.logging.log4j.Level;

import net.lightskin.farworld.FarWorld;
import net.lightskin.farworld.world.biomes.FarWorldOverworldBiomes;
import net.lightskin.farworld.world.biomes.RegionEnforcer;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class FarWorldGenLayer extends GenLayer
{
    private final GenLayer friend;

    public FarWorldGenLayer(long p_i2129_1_, GenLayer afriend)
    {
        super(p_i2129_1_);
        friend = afriend;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long seed)
    {
        super.initWorldGenSeed(seed);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight)
    {
    	int[] b = friend.getInts(areaX, areaY, areaWidth, areaHeight);
		Biome tmpa = RegionEnforcer.enforce(areaX * 4,areaY * 4); //don't know why i need to mult by 4 but whatever
		if(tmpa != null) {
			//FarWorld.logger.log(Level.INFO, tmpa.getBiomeName() + "|" + areaX + "," + areaY);
			for(int w = 0; w < areaWidth * areaHeight; ++w) {

    				b[w] = Biome.getIdForBiome(tmpa);
    		}
		}
		//else
			//FarWorld.logger.log(Level.INFO, "NULL|" + areaX + "," + areaY);
        return b;
    }
}
